name: ios

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

jobs:
  unit-tests:
    strategy:
      matrix:
        device:
          - "iPhone 12 (14.3)"
    runs-on: macos-10.15
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.3'

    - name: List all simulators
      run: xcrun instruments -s

    - name: Start Simulator
      run: |
        UDID=$(
          xcrun instruments -s |
          awk \
            -F ' *[][]' \
            -v 'device=${{ matrix.device }}' \
            '$1 == device { print $2 }'
        )
        xcrun simctl boot "${UDID:?No Simulator with this name found}"

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Install Appium
      run: npm install -g appium@beta --chromedriver-skip-install

    - name: Start Appium server
      run: appium --log-timestamp --log-no-colors > appium.log &

    - name: Poll for Appium Server
      run: |
        until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:4723/wd/hub/sessions); do
          sleep 5
        done

    - name: Test in iOS
      run: npm run test:ios

    - name: Upload Appium log
      uses: actions/upload-artifact@v2
      with:
        name: appium
        path: appium.log
